// tokyo-night.ts — a Monaco editor theme based on the Tokyo Night color scheme.
// Passed to monaco.editor.defineTheme(); see editor.tsx.

export const tokyoNight = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'a9b1d6' },
    { token: 'comment', foreground: '565f89', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'bb9af7' },
    { token: 'operator', foreground: '89ddff' },
    { token: 'delimiter', foreground: '9aa5ce' },
    { token: 'string', foreground: '9ece6a' },
    { token: 'string.escape', foreground: '89ddff' },
    { token: 'number', foreground: 'ff9e64' },
    { token: 'regexp', foreground: 'b4f9f8' },
    { token: 'type', foreground: '2ac3de' },
    { token: 'type.identifier', foreground: '2ac3de' },
    { token: 'namespace', foreground: '2ac3de' },
    { token: 'identifier', foreground: 'c0caf5' },
    { token: 'function', foreground: '7aa2f7' },
    { token: 'variable', foreground: 'c0caf5' },
    { token: 'constant', foreground: 'ff9e64' },
    { token: 'tag', foreground: 'f7768e' },
    { token: 'attribute.name', foreground: 'bb9af7' },
    { token: 'attribute.value', foreground: '9ece6a' },
  ],
  colors: {
    'editor.background': '#1a1b26',
    'editor.foreground': '#a9b1d6',
    'editor.lineHighlightBackground': '#1f2335',
    'editor.selectionBackground': '#283457',
    'editorCursor.foreground': '#c0caf5',
    'editorLineNumber.foreground': '#3b4261',
    'editorLineNumber.activeForeground': '#737aa2',
    'editorIndentGuide.background': '#1f2335',
    'editorIndentGuide.activeBackground': '#292e42',
    'editorWhitespace.foreground': '#3b4261',
    'editorWidget.background': '#16161e',
    'editorWidget.border': '#15161e',
    'editorSuggestWidget.background': '#16161e',
    'editorSuggestWidget.border': '#15161e',
    'editorSuggestWidget.selectedBackground': '#283457',
    'editorHoverWidget.background': '#16161e',
    'editorHoverWidget.border': '#15161e',
    'editorError.foreground': '#f7768e',
    'editorWarning.foreground': '#e0af68',
    'editorGutter.background': '#1a1b26',
    'minimap.background': '#1a1b26',
    'scrollbarSlider.background': '#3b426188',
    'scrollbarSlider.hoverBackground': '#3b4261bb',
    'scrollbarSlider.activeBackground': '#3b4261',
  },
};
